name: aws-tests

on:
  workflow_dispatch:

env:
  GAR_PROJECT_ID: hazelcast-33
  GAR_REGION: us-east1
  GAR_REPO: auto-discovery-test-suite
  AWS_REGION: us-east-1

defaults:
  run:
    working-directory: aws-discovery-suite/terraform/test

jobs:
  build:
    uses: ./.github/workflows/build-artifact.yml
    secrets: inherit

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: ['ec2_cl_to_ec2_m', 'ec2_cl_to_fargate_ecs_m', 'fargate_ecs_cl_to_ec2_m', 'fargate_ecs_cl_to_fargate_ecs_m']
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Auto Discovery Test Suite
        uses: actions/checkout@v3
        with:
          repository: hazelcast/auto-discovery-test-suite
          token: ${{ secrets.PAT }}
          path: aws-discovery-suite

      - name: Download hazelcast.jar
        uses: actions/download-artifact@v3
        with:
          name: hazelcast.jar
          path: aws-discovery-suite/terraform/tools

      - name: Download aws-discovery-client.jar
        uses: actions/download-artifact@v3
        with:
          name: aws-discovery-client.jar
          path: aws-discovery-suite/terraform/tools/client

      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.4
          terraform_wrapper: false

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Tests
        run: |
          go test -v -timeout 20m -run TestSuite -suite ${{ matrix.suite }} -member-image ${{ needs.build.outputs.HZ_IMG }} -client-image ${{ needs.build.outputs.CL_IMG }}
