name: aws-tests
on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: hazelcast-33
  GAR_REGION: us-east1
  GAR_PROJECT: hazelcast-33
  GAR_REPO: auto-discovery-test-suite
  
jobs:
  build:
    name: AWS Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Auto Discovery Test Suite
        uses: actions/checkout@v3
        with:
          repository: cheels/auto-discovery-test-suite
          token: ${{ secrets.PAT }} 
          path: aws-discovery-suite
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master
        
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          architecture: x64
          distribution: adopt
          cache: 'maven'
          
      - name: Setup Local Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build hazelcast jar
        working-directory: master
        run: |
          echo ${GITHUB_WORKSPACE}
          HAZELCAST_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "HAZELCAST_VERSION=${HAZELCAST_VERSION}" >> $GITHUB_ENV

           ./mvnw -T 4 -B -V -e clean install \
           -Dfindbugs.skip \
           -Dcheckstyle.skip \
           -Dpmd.skip=true \
           -Dspotbugs.skip \
           -Denforcer.skip \
           -Dmaven.javadoc.skip \
           -DskipTests \
           -Dlicense.skip=true \
           -Drat.skip=true \
           -Dspotless.check.skip=true \
           -Dattribution.skip \
           -Danimal.sniffer.skip=true \
           -Dmaven.source.skip=true
            cp hazelcast/target/hazelcast-*-SNAPSHOT.jar ${GITHUB_WORKSPACE}/aws-discovery-suite/terraform/tools/hazelcast.jar
            ls ${GITHUB_WORKSPACE}/aws-discovery-suite/terraform/tools

      - name: Build client jar
        working-directory: aws-discovery-suite/terraform/tools/client
        run: |
          mvn versions:set-property -Dproperty=hazelcast.version -DnewVersion=$HAZELCAST_VERSION
          mvn clean package
          mv target/aws-discovery-client.jar aws-discovery-client.jar

      - name: Authenticate to GAR
        uses: docker/login-action@v2
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build Hazelcast Image
        working-directory: aws-discovery-suite/terraform/tools
        run: |
          HZ_IMG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/$(uuidgen):3d"
          docker build -f Dockerfile -t ${HZ_IMG} .
          docker push ${HZ_IMG}
         
      - name: Build Client Image
        working-directory: aws-discovery-suite/terraform/tools/client
        run: |
          CL_IMG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/$(uuidgen):3d"
          docker build -f Dockerfile -t ${CL_IMG} .
          docker push ${CL_IMG}

      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.1.8

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
